apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/uitcontainerregistry-pull-secret
  - ../../components/postgres
  - drupal-deployment.yaml
  - drupal-default-pvc.yaml
  - drupal-default-files-pvc.yaml
  - drupal-service.yaml
  - ingress.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
  - secret-db.yaml
configMapGenerator:
  - name: settings-php
    files:
      - settings.php=settings.php
