apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/uitcontainerregistry-pull-secret
  - drupal-deployment.yaml
  - nginx-deployment.yaml
  - drupal-service.yaml
  - drupal-pvc.yaml
  - ingress.yaml