apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/drupal11
  - ../../base/uitcontainerregistry-pull-secret
patches:
  - path: patches/nginx-image.yaml
  - path: patches/drupal-image.yaml
