apiVersion: v1
kind: Service
metadata:
  name: ${app_name}-mariadb
spec:
  selector:
    app: ${app_name}-mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
