apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${app_name}-nginx
  annotations:
    cert-manager.io/cluster-issuer: harica
    cert-manager.io/private-key-algorithm: ECDSA
    cert-manager.io/usages: "digital signature"
    cert-manager.io/private-key-rotation-policy: Always
    # When set only available from
    # nginx.ingress.kubernetes.io/whitelist-source-range: 129.242.0.0/16,2001:700:200::/48

spec:
  ingressClassName: nginx
  rules:
  - host: ${app_name}.${rail_region}.${rail_env}.rail.uib.no
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httpd
            port:
              number: 80
  tls:
  - hosts:
    - ${app_name}.${rail_region}.${rail_env}.rail.uib.no
    secretName: ${app_name}.${rail_region}.${rail_env}.rail.uib.no-tls