apiVersion: v1
kind: Service
metadata:
  name: ${app_name}-php-fpm
  labels:
    app: ${app_name}-php-fpm
spec:
  selector:
    app: ${app_name}-php-fpm
  ports:
    - name: fastcgi
      port: 9000
      targetPort: 9000
    - name: metrics
      port: 9253
      targetPort: 9253
