apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/php-fpm
  - ../../components/nginx
  - run-cron-jobs.yaml
  - pvc.yaml
configMapGenerator:
  - name: nginx-config
    files:
      - default.conf=nginx.conf
  - name: phpfpm-config
    files:
      - zz-docker.conf=www.conf
  - name: php-config
    files:
      - 99-php-fpm.ini=php.ini
